name: Validate 

on: 
  push:
    paths:
      - force-app/**

jobs:
  run-test-classes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --global
          sf --version
      - name: Login To Org
        run: |
          sf org login sfdx-url --set-default --alias devorg --sfdx-url-file <(echo "${{ secrets.SFDX_AUTH_URL_FILE_DEV }}") 
      - name: Run Test Classes
        run: |
          sf apex run test --test-level RunLocalTests -w 15
